# This is a basic workflow to help you get started with Actions
name: deploy-application

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Install project dependencies, test and build
      - run: npm install
      - run: npm run build

      # Install AWS CLI
      - uses: jakejarvis/s3-sync-action@master
      - run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME }}/latest
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCCESS_KEY: ${{ secrets.AWS_SECRET_ACCCESS_KEY }}
